name: aqsa_namaz_timing
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  flutter_riverpod: ^2.1.3
  http: ^0.13.5
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.3
  slide_countdown: ^0.4.0
  flutter_qiblah: ^2.1.0
  flutter_svg: ^1.1.6
  geolocator: ^9.0.2
  shared_preferences: ^2.0.15
  fluttertoast: ^8.1.2
  motion: ^1.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_localizations:
    sdk: flutter
  permission_handler: ^10.2.0
  flutter_native_splash: ^2.2.9
  csc_picker: ^0.2.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/logo.png"
  image_path: "assets/logo.png"
  min_sdk_android: 19
# The following section is specific to Flutter packages.
flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo.png"
flutter_localizations:
  sdk: flutter
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
